/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_digitalsquid_netspoofer_JNI */

#ifndef _Included_uk_digitalsquid_netspoofer_JNI
#define _Included_uk_digitalsquid_netspoofer_JNI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
