/*
 * This file is part of Network Spoofer for Android.
 * Network Spoofer lets you change websites on other people’s computers
 * from an Android phone.
 * Copyright (C) 2011 Will Shackleton
 *
 * Network Spoofer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Network Spoofer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Network Spoofer, in the file COPYING.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package uk.digitalsquid.netspoofer.config;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import android.content.Context;
import android.os.Build;
import android.util.Log;

public final class ProcessRunner implements LogConf {
	private ProcessRunner() {}
	
	public static final int runProcess(Context context, String... args) throws IOException {
		return runProcess(context, null, args);
	}

	/**
	 * Runs a process with the given environment and args
	 * @param env
	 * @param args
	 * @return
	 * @throws IOException
	 */
	public static final int runProcess(Context context, Map<String, String> env, String... args) throws IOException {
		return runProcess(context, env, (List<String>) null, args);
	}
	
	/**
	 * Runs a process with an environment and saves the output to output.
	 * @param env The environment
	 * @param output A list to put the command's output in.
	 * @param args The program args
	 * @return
	 * @throws IOException
	 */
	public static final int runProcess(Context context, Map<String, String> env, List<String> output, String... args) throws IOException {
		Process proc;
		if(Build.VERSION.SDK_INT >= 9) { // 2.2 doesn't like this method
			ProcessBuilder pb = new ProcessBuilder(args);
			writeEnvConfigFile(context, env);
			proc = pb.start();
		} else {
			if(env != null) {
				Map<String, String> systemEnv = System.getenv(); // We also must include this
				Map<String, String> combinedEnv = new HashMap<String, String>();
				combinedEnv.putAll(env);
				combinedEnv.putAll(systemEnv);
				
				String[] envArray = new String[combinedEnv.size()];
				int i = 0;
				for(String key : combinedEnv.keySet()) {
					envArray[i++] = String.format("%s=%s", key, combinedEnv.get(key));
				}
				proc = Runtime.getRuntime().exec(args, envArray);
			} else {
				proc = Runtime.getRuntime().exec(args);
			}
		}
		BufferedReader cout = new BufferedReader(new InputStreamReader(proc.getInputStream()));
		BufferedReader cerr = new BufferedReader(new InputStreamReader(proc.getErrorStream()));
		boolean running = true;
		while(running) {
			while(cout.ready()) {
				String msg = cout.readLine();
				if(output != null) output.add(msg);
				Log.d(TAG, "cout: " + msg);
			}
			while(cerr.ready()) {
				String msg = cerr.readLine();
				if(output != null) output.add(msg);
				Log.d(TAG, "cerr: " + msg);
			}
			try {
				proc.exitValue();
				running = false;
				cout.close();
				cerr.close();
				return proc.exitValue();
			}
			catch (IllegalThreadStateException e) { } // Not done
			try { Thread.sleep(50); } catch (InterruptedException e) { }
		}
		return 0;
	}
	
	/**
	 * Writes the <code>config</code> file with the env paramaters.
	 * The config file is changed before the process is run now.
	 * This is because of Android 4.3 not liking environment variables.
	 * @param env
	 */
	public static final void writeEnvConfigFile(Context context, Map<String, String> env) {
		HashMap<String, String> fullEnv = env == null ?
				new HashMap<String, String>() :
				new HashMap<String, String>(env);
		fullEnv.put("PATH", "/usr/local/bin:/usr/bin:/usr/sbin:/bin:$PATH");
		fullEnv.put("TERM", "linux");
		fullEnv.put("HOME", "/root");
		String scriptPath = FileInstaller.getScriptPath(context, "config");
		FileWriter writer = null;
		try {
			writer = new FileWriter(scriptPath, false);
			writer.write("# Config generated by writeEnvConfigFile\n");
			for(Entry<String, String> entry : fullEnv.entrySet()) {
				writer.write(String.format("export %s=\"%s\"\n", entry.getKey(), entry.getValue()));
			}
			writer.write("\n");
		} catch (FileNotFoundException e) {
			Log.e(TAG, "Failed to write env config file", e);
		} catch (IOException e) {
			Log.e(TAG, "Failed to write env config file", e);
		} finally {
			if(writer != null)
				try { writer.close(); } catch (IOException e) { }
		}
	}
}
