/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_digitalsquid_netspoofer_JNI */

#ifndef _Included_uk_digitalsquid_netspoofer_JNI
#define _Included_uk_digitalsquid_netspoofer_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_digitalsquid_netspoofer_JNI
 * Method:    setExecutable
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_digitalsquid_netspoofer_JNI_setExecutable
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
