#!/system/bin/sh
# This file is part of Network Spoofer for Android.
# Network Spoofer - change and mess with webpages and the internet on
# other people's computers
# Copyright (C) 2011 Will Shackleton
#
# Network Spoofer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Network Spoofer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Network Spoofer, in the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.

# First arg is always path to config file.
. $1

set -x

echo "Starting..."
echo "Busybox: $BB"
echo "Env:"
env

echo 1 > /proc/sys/net/ipv4/ip_forward

echo "INFO: Mount data"
$BB mount
# Create folder
# If no BB, then this will use builtins.
$BB mkdir -p $DEB || 
(
	# Can't create dir, remount rw then try again
	echo "Couldn't create mount directory, trying to remount filesystems RW"
	
	# Try everything
	$BB mount -o remount,rw /data/local
	$BB mount -o remount,rw /data
	$BB mount -o remount,rw /
	
	echo "INFO: New mount data"
	$BB mount
	
	# Try again
	$BB mkdir -p $DEB
)

$BB ls -la $DEB

echo "Loading FS from file $DEBIMG to loop $LOOPDEV ($LOOPNUM) at mountpoint $DEB"

$BB mknod $LOOPDEV b 7 $LOOPNUM
$BB losetup $LOOPDEV $DEBIMG
$BB mount -o loop $LOOPDEV $DEB

$BB mount -t devpts devpts $DEB/dev/pts
$BB mount -t proc proc $DEB/proc
$BB mount -t sysfs sysfs $DEB/sys

# Debug
$BB ls -la $DEB
echo "Loop device:"
$BB ls -l $LOOPDEV
