#!/system/bin/sh
# This file is part of Network Spoofer for Android.
# Network Spoofer - change and mess with webpages and the internet on
# other people's computers
# Copyright (C) 2011 Will Shackleton
#
# Network Spoofer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Network Spoofer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Network Spoofer, in the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.

# First arg is always path to config file.
. $1

echo 1 > /proc/sys/net/ipv4/ip_forward

# Get all args but first
shift

echo "Starting environment"
$BB chroot $DEB $@
echo "Environment done."
